export const STUDENTS = [
  { id: 1, name: "Aarav Sharma", rollNo: "101", marks: 78, gender: "Male", status: "Pass" },
  { id: 2, name: "Sita Thapa", rollNo: "102", marks: 35, gender: "Female", status: "Fail" },
  { id: 3, name: "Rohan Singh", rollNo: "103", marks: 88, gender: "Male", status: "Pass" },
  { id: 4, name: "Anjali Karki", rollNo: "104", marks: 59, gender: "Female", status: "Pass" },
  { id: 5, name: "Nabin Rai", rollNo: "105", marks: 42, gender: "Male", status: "Pass" },
  { id: 6, name: "Pooja Shrestha", rollNo: "106", marks: 91, gender: "Female", status: "Pass" },
  { id: 7, name: "Suresh Adhikari", rollNo: "107", marks: 23, gender: "Male", status: "Fail" },
  { id: 8, name: "Kriti Bhandari", rollNo: "108", marks: 67, gender: "Female", status: "Pass" },
  { id: 9, name: "Amit Joshi", rollNo: "109", marks: 49, gender: "Male", status: "Pass" },
  { id: 10, name: "Nisha Gurung", rollNo: "110", marks: 38, gender: "Female", status: "Fail" },

  { id: 11, name: "Bikash KC", rollNo: "111", marks: 55, gender: "Male", status: "Pass" },
  { id: 12, name: "Manisha Pandey", rollNo: "112", marks: 72, gender: "Female", status: "Pass" },
  { id: 13, name: "Kiran Magar", rollNo: "113", marks: 61, gender: "Male", status: "Pass" },
  { id: 14, name: "Sneha Pokhrel", rollNo: "114", marks: 44, gender: "Female", status: "Pass" },
  { id: 15, name: "Rajiv Chaudhary", rollNo: "115", marks: 29, gender: "Male", status: "Fail" },
  { id: 16, name: "Ritika Lama", rollNo: "116", marks: 85, gender: "Female", status: "Pass" },
  { id: 17, name: "Deepak Yadav", rollNo: "117", marks: 90, gender: "Male", status: "Pass" },
  { id: 18, name: "Pratiksha Koirala", rollNo: "118", marks: 33, gender: "Female", status: "Fail" },
  { id: 19, name: "Sanjay Mishra", rollNo: "119", marks: 47, gender: "Male", status: "Pass" },
  { id: 20, name: "Anish Shah", rollNo: "120", marks: 66, gender: "Male", status: "Pass" },

  { id: 21, name: "Ramesh Tiwari", rollNo: "121", marks: 58, gender: "Male", status: "Pass" },
  { id: 22, name: "Bina Tamang", rollNo: "122", marks: 41, gender: "Female", status: "Pass" },
  { id: 23, name: "Suraj Bohara", rollNo: "123", marks: 37, gender: "Male", status: "Fail" },
  { id: 24, name: "Kajal Mehta", rollNo: "124", marks: 74, gender: "Female", status: "Pass" },
  { id: 25, name: "Ashok Basnet", rollNo: "125", marks: 82, gender: "Male", status: "Pass" },
  { id: 26, name: "Sarina Khadka", rollNo: "126", marks: 69, gender: "Female", status: "Pass" },
  { id: 27, name: "Mahesh Rawat", rollNo: "127", marks: 40, gender: "Male", status: "Pass" },
  { id: 28, name: "Isha Verma", rollNo: "128", marks: 28, gender: "Female", status: "Fail" },
  { id: 29, name: "Prakash Shahi", rollNo: "129", marks: 53, gender: "Male", status: "Pass" },
  { id: 30, name: "Neha Agarwal", rollNo: "130", marks: 95, gender: "Female", status: "Pass" },
];
